### ISSUE TITLE
很有趣的项目

### ISSUE THREAD

**Issue by nvv5** [pkmq24/smm2-multiplayer-OCR#1]
关于识别率的问题，之前恰好用过pytesseract，如果只是识别杰哥的话，建议自己用jTessBoxEditor训练字库，个人感觉还不错。太晚了老哥的脚本还没来得及测试，不知道你的视频是本地分割成图片进行识别的吗？没来得及细看你的画面是怎么处理的。另外，啥时候来个大数据预测啊

**Comment by pkmq24** [comment]
整个项目都挺基础的 所以用pytesseract就这么跑了
画面处理比较笨比 需要一个屏幕开着直播 然后对屏幕截图 再取坐标

大数据预测需要足够数据量 我现在的这种写法没法得到足够数据量hhh 今后再说吧
